sudo: false

language: python

python:
  - 2.6

install:
  - pip install pytest
  - pip install coveralls

script: coverage run --source suricate -m py.test

after_success: coveralls

notifications:
  email: true
