sudo: false

language: python

python:
  - 2.7

before_install:
  - pip install pytest==3.5.0

install:
  - pip install pytz
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py install

services:
  - redis-server

script:
    - coverage run --source suricate -m py.test

after_success: coveralls

notifications:
  email: true
