#!/bin/bash

rm -f .coverage
# coverage run --source suricate -m pytest --capture=no $1
coverage run --source suricate -m pytest --disable-warnings $1

if [ "$1" == "--acs" ]
then
    coverage report --include "./suricate/*"
else
    coverage report --include "./suricate/*" --omit "./suricate/services.py"
fi
