#!/bin/bash
# chkconfig: 345 99 01
# description: DISCOS monitoring program

# Location of this file: /etc/rc.d/init.d/suricate-server

# Source function library.
. /etc/init.d/functions

name="suricate-server"
pidfile="/var/run/$name.pid"
exec="/alma/ACS-FEB2017/Python/bin/$name"
logfile="/tmp/suricate.log"

start() {
        echo "Starting $name..."
        su - discos -c "nohup $exec start >> $logfile 2>&1 &"
        touch $pidfile
        return 0
}

stop() {
        echo "Shutting down $name..."
        su - discos -c "nohup $exec stop >> $logfile 2>&1 &"
        rm -f $pidfile
        return 0
}

status() {
   if [ -e $pidfile ]; then
      echo "$name is running"
   else
      echo "$name is NOT running"
      exit 1
   fi
}

case "$1" in
    start)
        start
        status
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        status
        ;;
    *)
        echo "Usage: $name {start|stop|status|restart}"
 exit 1
        ;;
esac
exit $?
