#!/usr/bin/env python
from __future__ import print_function

import os
import sys
import fcntl
from subprocess import check_output, STDOUT
import requests
from suricate import server
from argparse import ArgumentParser


parser = ArgumentParser(description='http://suricate.readthedocs.org/')
parser.add_argument('--no_components', action='store_true')
parser.add_argument('action', choices=['start', 'stop'])

args = parser.parse_args()

from suricate.configuration import COMPONENTS, PORT, BASEURL

if args.action == 'start':
    # Check if ACS is ready
    output = check_output(['acsStatus'], stderr=STDOUT)
    if 'Unable to determine manager' in output:
        print('ERROR: ACS is not running')
        sys.exit(1)
    if args.no_components:
        server.start()
    else:
        server.start(COMPONENTS)
elif args.action == 'stop':
    url = BASEURL + '/publisher/api/v0.1/stop'
    msg = ''
    try:
        requests.post(url)
        print('A "stop" request has been sent to the server')
    except requests.exceptions.ConnectionError:
        print('The server was already stopped...')
