#!/usr/bin/env python

from shutil import copyfile
from argparse import ArgumentParser
import os
import io
import yaml
from suricate.configuration import default_config
from suricate.paths import (
    config_dir,
    config_file,
    template_dir,
)


parser = ArgumentParser()
parser.add_argument(
    '-t',
    '--template',
    required=True,
    choices=('default', 'srt', 'medicina', 'noto'),
    help='Telescope configuration'
)
args = parser.parse_args()


try:
    os.mkdir(config_dir)
except OSError:
    pass  # The directory already exists

if args.template == 'default':
    with io.open(config_file, 'w', encoding='utf-8') as outfile:
        yaml.dump(default_config, outfile)
    print(f'{config_file} created!')
else:
    template = f'{args.template}.yaml'
    source_file = os.path.join(template_dir, template)
    copyfile(source_file, config_file)
    print(f'{config_file} created from {template}!')
